name: stress_management_app

description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  tflite: ^1.1.2
  image_picker: ^1.0.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  get: ^4.6.5
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter 

  camera:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_Regular.ttf
        - asset: assets/fonts/NunitoSans_Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_ExtraBold.ttf
          weight: 800

